import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { provinces, addresses } from "../../drizzle/schema";

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

const drcProvinces = [
  {
    id: "prov_kinshasa",
    name: "Kinshasa",
    code: "KIN",
    population: 17071000,
    areaSqkm: "9965.00",
    capitalCity: "Kinshasa",
    targetAddresses: 500000,
  },
  {
    id: "prov_kongo_central",
    name: "Kongo Central",
    code: "KOC",
    population: 5575000,
    areaSqkm: "53920.00",
    capitalCity: "Matadi",
    targetAddresses: 150000,
  },
  {
    id: "prov_kwango",
    name: "Kwango",
    code: "KWA",
    population: 2218000,
    areaSqkm: "89974.00",
    capitalCity: "Kenge",
    targetAddresses: 80000,
  },
  {
    id: "prov_kwilu",
    name: "Kwilu",
    code: "KWI",
    population: 6682000,
    areaSqkm: "78219.00",
    capitalCity: "Bandundu",
    targetAddresses: 120000,
  },
  {
    id: "prov_mai_ndombe",
    name: "Mai-Ndombe",
    code: "MND",
    population: 2495000,
    areaSqkm: "127465.00",
    capitalCity: "Inongo",
    targetAddresses: 60000,
  },
  {
    id: "prov_kasai",
    name: "Kasaï",
    code: "KAS",
    population: 3199000,
    areaSqkm: "95631.00",
    capitalCity: "Tshikapa",
    targetAddresses: 90000,
  },
  {
    id: "prov_kasai_central",
    name: "Kasaï-Central",
    code: "KAC",
    population: 3199000,
    areaSqkm: "59111.00",
    capitalCity: "Kananga",
    targetAddresses: 100000,
  },
  {
    id: "prov_kasai_oriental",
    name: "Kasaï-Oriental",
    code: "KAO",
    population: 3199000,
    areaSqkm: "9481.00",
    capitalCity: "Mbuji-Mayi",
    targetAddresses: 110000,
  },
  {
    id: "prov_lomami",
    name: "Lomami",
    code: "LOM",
    population: 2569000,
    areaSqkm: "56426.00",
    capitalCity: "Kabinda",
    targetAddresses: 70000,
  },
  {
    id: "prov_sankuru",
    name: "Sankuru",
    code: "SAN",
    population: 2380000,
    areaSqkm: "104331.00",
    capitalCity: "Lusambo",
    targetAddresses: 65000,
  },
  {
    id: "prov_maniema",
    name: "Maniema",
    code: "MAE",
    population: 2856000,
    areaSqkm: "132250.00",
    capitalCity: "Kindu",
    targetAddresses: 75000,
  },
  {
    id: "prov_south_kivu",
    name: "South Kivu",
    code: "SKI",
    population: 7066000,
    areaSqkm: "65070.00",
    capitalCity: "Bukavu",
    targetAddresses: 140000,
  },
  {
    id: "prov_north_kivu",
    name: "North Kivu",
    code: "NKI",
    population: 8567000,
    areaSqkm: "59483.00",
    capitalCity: "Goma",
    targetAddresses: 160000,
  },
  {
    id: "prov_ituri",
    name: "Ituri",
    code: "ITU",
    population: 5784000,
    areaSqkm: "65658.00",
    capitalCity: "Bunia",
    targetAddresses: 95000,
  },
  {
    id: "prov_haut_uele",
    name: "Haut-Uélé",
    code: "HAU",
    population: 1920000,
    areaSqkm: "89683.00",
    capitalCity: "Isiro",
    targetAddresses: 55000,
  },
  {
    id: "prov_tshopo",
    name: "Tshopo",
    code: "TSH",
    population: 2614000,
    areaSqkm: "199567.00",
    capitalCity: "Kisangani",
    targetAddresses: 85000,
  },
  {
    id: "prov_bas_uele",
    name: "Bas-Uélé",
    code: "BAU",
    population: 1559000,
    areaSqkm: "148331.00",
    capitalCity: "Buta",
    targetAddresses: 50000,
  },
  {
    id: "prov_nord_ubangi",
    name: "Nord-Ubangi",
    code: "NOU",
    population: 1482000,
    areaSqkm: "56644.00",
    capitalCity: "Gbadolite",
    targetAddresses: 45000,
  },
  {
    id: "prov_mongala",
    name: "Mongala",
    code: "MON",
    population: 2104000,
    areaSqkm: "58141.00",
    capitalCity: "Lisala",
    targetAddresses: 60000,
  },
  {
    id: "prov_sud_ubangi",
    name: "Sud-Ubangi",
    code: "SOU",
    population: 2744000,
    areaSqkm: "51648.00",
    capitalCity: "Gemena",
    targetAddresses: 70000,
  },
  {
    id: "prov_equateur",
    name: "Équateur",
    code: "EQU",
    population: 2103000,
    areaSqkm: "103902.00",
    capitalCity: "Mbandaka",
    targetAddresses: 65000,
  },
  {
    id: "prov_tshuapa",
    name: "Tshuapa",
    code: "TSU",
    population: 1999000,
    areaSqkm: "132957.00",
    capitalCity: "Boende",
    targetAddresses: 55000,
  },
  {
    id: "prov_tanganyika",
    name: "Tanganyika",
    code: "TAN",
    population: 3060000,
    areaSqkm: "134940.00",
    capitalCity: "Kalemie",
    targetAddresses: 80000,
  },
  {
    id: "prov_haut_lomami",
    name: "Haut-Lomami",
    code: "HAL",
    population: 3211000,
    areaSqkm: "108204.00",
    capitalCity: "Kamina",
    targetAddresses: 85000,
  },
  {
    id: "prov_lualaba",
    name: "Lualaba",
    code: "LUA",
    population: 2570000,
    areaSqkm: "121308.00",
    capitalCity: "Kolwezi",
    targetAddresses: 90000,
  },
  {
    id: "prov_haut_katanga",
    name: "Haut-Katanga",
    code: "HAK",
    population: 6295000,
    areaSqkm: "132425.00",
    capitalCity: "Lubumbashi",
    targetAddresses: 150000,
  },
];

const sampleAddresses = [
  // Kinshasa samples
  {
    id: "addr_kin_001",
    fullAddress: "Avenue de la Libération, Gombe, Kinshasa",
    zone: "Zone 1",
    street: "Avenue de la Libération",
    doorNumber: "245",
    quartier: "Gombe",
    commune: "Gombe",
    provinceId: "prov_kinshasa",
    latitude: "-4.3276",
    longitude: "15.3136",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.95",
  },
  {
    id: "addr_kin_002",
    fullAddress: "Boulevard du 30 Juin, Kalamu, Kinshasa",
    zone: "Zone 2",
    street: "Boulevard du 30 Juin",
    doorNumber: "1520",
    quartier: "Kalamu",
    commune: "Kalamu",
    provinceId: "prov_kinshasa",
    latitude: "-4.3389",
    longitude: "15.3214",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.92",
  },
  {
    id: "addr_kin_003",
    fullAddress: "Avenue Kalemie, Lemba, Kinshasa",
    zone: "Zone 3",
    street: "Avenue Kalemie",
    doorNumber: "78",
    quartier: "Lemba",
    commune: "Lemba",
    provinceId: "prov_kinshasa",
    latitude: "-4.3897",
    longitude: "15.2967",
    verificationStatus: "pending" as const,
    dataSource: "crowdsourced" as const,
    confidenceScore: "0.78",
  },
  {
    id: "addr_kin_004",
    fullAddress: "Rue de la Paix, Ngaliema, Kinshasa",
    zone: "Zone 4",
    street: "Rue de la Paix",
    doorNumber: "412",
    quartier: "Ngaliema",
    commune: "Ngaliema",
    provinceId: "prov_kinshasa",
    latitude: "-4.3712",
    longitude: "15.2689",
    verificationStatus: "unverified" as const,
    dataSource: "ai_detected" as const,
    confidenceScore: "0.65",
  },
  // Lubumbashi samples
  {
    id: "addr_lub_001",
    fullAddress: "Avenue Mobutu, Lubumbashi",
    zone: "Centre",
    street: "Avenue Mobutu",
    doorNumber: "89",
    quartier: "Centre-Ville",
    commune: "Lubumbashi",
    provinceId: "prov_haut_katanga",
    latitude: "-11.6792",
    longitude: "27.4797",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.90",
  },
  {
    id: "addr_lub_002",
    fullAddress: "Boulevard Lumumba, Kenya, Lubumbashi",
    zone: "Kenya",
    street: "Boulevard Lumumba",
    doorNumber: "234",
    quartier: "Kenya",
    commune: "Lubumbashi",
    provinceId: "prov_haut_katanga",
    latitude: "-11.6456",
    longitude: "27.4823",
    verificationStatus: "pending" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.85",
  },
  // Goma samples
  {
    id: "addr_gom_001",
    fullAddress: "Avenue des Volcans, Goma",
    zone: "Lac Vert",
    street: "Avenue des Volcans",
    doorNumber: "56",
    quartier: "Lac Vert",
    commune: "Goma",
    provinceId: "prov_north_kivu",
    latitude: "-1.6740",
    longitude: "29.2228",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.88",
  },
  {
    id: "addr_gom_002",
    fullAddress: "Rue de Virunga, Himbi, Goma",
    zone: "Himbi",
    street: "Rue de Virunga",
    doorNumber: "123",
    quartier: "Himbi",
    commune: "Goma",
    provinceId: "prov_north_kivu",
    latitude: "-1.6812",
    longitude: "29.2156",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.91",
  },
  // Bukavu samples
  {
    id: "addr_buk_001",
    fullAddress: "Avenue Patrice Lumumba, Bukavu",
    zone: "Ibanda",
    street: "Avenue Patrice Lumumba",
    doorNumber: "345",
    quartier: "Ibanda",
    commune: "Ibanda",
    provinceId: "prov_south_kivu",
    latitude: "-2.5085",
    longitude: "28.8473",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.93",
  },
  {
    id: "addr_buk_002",
    fullAddress: "Boulevard du Lac, Kadutu, Bukavu",
    zone: "Kadutu",
    street: "Boulevard du Lac",
    doorNumber: "178",
    quartier: "Kadutu",
    commune: "Kadutu",
    provinceId: "prov_south_kivu",
    latitude: "-2.5156",
    longitude: "28.8512",
    verificationStatus: "pending" as const,
    dataSource: "crowdsourced" as const,
    confidenceScore: "0.76",
  },
  // Kisangani samples
  {
    id: "addr_kis_001",
    fullAddress: "Avenue Lumumba, Kisangani",
    zone: "Makiso",
    street: "Avenue Lumumba",
    doorNumber: "267",
    quartier: "Makiso",
    commune: "Makiso",
    provinceId: "prov_tshopo",
    latitude: "0.5167",
    longitude: "25.1833",
    verificationStatus: "verified" as const,
    dataSource: "manual_survey" as const,
    confidenceScore: "0.87",
  },
  {
    id: "addr_kis_002",
    fullAddress: "Rue du Commerce, Tshopo, Kisangani",
    zone: "Tshopo",
    street: "Rue du Commerce",
    doorNumber: "89",
    quartier: "Tshopo",
    commune: "Tshopo",
    provinceId: "prov_tshopo",
    latitude: "0.5234",
    longitude: "25.1912",
    verificationStatus: "unverified" as const,
    dataSource: "ai_detected" as const,
    confidenceScore: "0.62",
  },
];

export async function seedDatabase() {
  try {
    // Insert provinces
    for (const province of drcProvinces) {
      await db.insert(provinces).values(province).onConflictDoUpdate({
        target: provinces.id,
        set: { name: province.name },
      });
    }

    // Insert sample addresses
    for (const address of sampleAddresses) {
      await db.insert(addresses).values(address).onConflictDoUpdate({
        target: addresses.id,
        set: { fullAddress: address.fullAddress },
      });
    }

    return {
      provinces: drcProvinces.length,
      addresses: sampleAddresses.length,
    };
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

